name: Manual Workflow

on:
# manual job GUI or github cli
  workflow_dispatch: 
    inputs:
      environment:
        description: "Choose environment" 
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production     
jobs:
  deploy:
    runs-on: ubuntu-latest #runner github

    steps:
      - name: Deploy Application
        run: echo "Deploying the application to ${{ inputs.environment }}"

          
          
