name: Push & Pull Request  Workflow
# Webhook base trigger on branches
on:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "src/**"
  pull_request:
    branches:
      - main
      - "release/**"
    paths:
      - "src/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Install dependencies and run tests
        working-directory: ./src
        run: |
          npm install
          npm test
